import type { PlayKind, VaultEntry } from "./vault";

/** Display month + ISO for library studies. Human days, Dec 2025 through Aug 2026. */
const STUDY_WHEN: Record<string, { date: string; when: string }> = {
  squircles: { date: "Dec 2025", when: "2025-12-11" },
  "arcade-pixel": { date: "Dec 2025", when: "2025-12-18" },
  holo: { date: "Dec 2025", when: "2025-12-27" },
  "pixel-brushes": { date: "Jan 2026", when: "2026-01-08" },
  typer: { date: "Jan 2026", when: "2026-01-19" },
  "fade-motion": { date: "Jan 2026", when: "2026-01-24" },
  ghosty: { date: "Feb 2026", when: "2026-02-08" },
  "kinetic-typography": { date: "Feb 2026", when: "2026-02-13" },
  "ransom-note": { date: "Feb 2026", when: "2026-02-21" },
  "chroma-glow": { date: "Mar 2026", when: "2026-03-04" },
  emboss: { date: "Mar 2026", when: "2026-03-12" },
  "color-depth": { date: "Mar 2026", when: "2026-03-22" },
  "vector-editor": { date: "Mar 2026", when: "2026-03-29" },
  amo: { date: "Apr 2026", when: "2026-04-07" },
  sandbox: { date: "Apr 2026", when: "2026-04-15" },
  midjourney: { date: "Apr 2026", when: "2026-04-22" },
  glossy: { date: "May 2026", when: "2026-05-06" },
  glow: { date: "May 2026", when: "2026-05-06" },
  bevel: { date: "May 2026", when: "2026-05-12" },
  flat: { date: "May 2026", when: "2026-05-12" },
  buttons: { date: "May 2026", when: "2026-05-13" },
  qr: { date: "May 2026", when: "2026-05-21" },
  athlos: { date: "May 2026", when: "2026-05-28" },
  loom: { date: "Jun 2026", when: "2026-06-04" },
  "fade-grid": { date: "Jun 2026", when: "2026-06-11" },
  "warp-grid": { date: "Jun 2026", when: "2026-06-18" },
  "ring-letters": { date: "Jun 2026", when: "2026-06-25" },
  "liquid-ui": { date: "Jul 2026", when: "2026-07-03" },
  "acme-login": { date: "Jul 2026", when: "2026-07-09" },
  "wave-grid": { date: "Jul 2026", when: "2026-07-16" },
  "drag-button": { date: "Jul 2026", when: "2026-07-22" },
  "op-grid": { date: "Jul 2026", when: "2026-07-28" },
  island: { date: "Aug 2026", when: "2026-08-03" },
  loader: { date: "Aug 2026", when: "2026-08-04" },
  accounts: { date: "Aug 2026", when: "2026-08-07" },
  pipeline: { date: "Aug 2026", when: "2026-08-11" },
  kanban: { date: "Aug 2026", when: "2026-08-11" },
  list: { date: "Aug 2026", when: "2026-08-11" },
  icons: { date: "Aug 2026", when: "2026-08-14" },
  charts: { date: "Aug 2026", when: "2026-08-18" },
  pie: { date: "Aug 2026", when: "2026-08-18" },
  bar: { date: "Aug 2026", when: "2026-08-18" },
  line: { date: "Aug 2026", when: "2026-08-18" },
  dropdown: { date: "Aug 2026", when: "2026-08-20" },
  dialog: { date: "Aug 2026", when: "2026-08-21" },
  sidebars: { date: "Aug 2026", when: "2026-08-22" },
  fohe: { date: "Aug 2026", when: "2026-08-24" },
  oymo: { date: "Aug 2026", when: "2026-08-25" },
  spina: { date: "Aug 2026", when: "2026-08-26" },
  "dia-gradient": { date: "Aug 2026", when: "2026-08-27" },
};

function study(
  slug: string,
  title: string,
  tags: string[],
  blurb: string,
  body: string[],
  playground: PlayKind,
  extra: Partial<VaultEntry> = {},
): VaultEntry {
  const dated = STUDY_WHEN[slug];
  return {
    slug,
    title,
    kind: "study",
    shelf: "components",
    tags,
    blurb,
    venue: "Component",
    authors: "Yousef Turk",
    body,
    links: [{ label: "vault", href: `/vault/${slug}` }],
    playground,
    ...extra,
    date: extra.date ?? dated?.date ?? "Aug 2026",
    when: extra.when ?? dated?.when ?? "2026-08-31",
  };
}

export const library: VaultEntry[] = [
  study(
    "typer",
    "The typer",
    ["CSS", "Type"],
    "The name types itself. Letters flicker through little pills, then they sit down.",
    [
      "Most headlines just fade. This one types. A wave runs the line. Each letter tries on a couple of states, then it stays.",
      "The name at the top of this site is the same component.",
    ],
    "typer",
  ),
  study(
    "ghosty",
    "Ghosty reveal",
    ["CSS", "Mask"],
    "Things that don't just fade. A soft mask slides, and the picture comes out of fog.",
    [
      "The trick is a tall, soft gradient laid over the box, several times taller than the image, then you slide it with mask-position.",
      "The orb on the home page uses this instead of popping in.",
    ],
    "ghosty",
  ),
  study(
    "squircles",
    "Apple's corners",
    ["CSS", "SVG"],
    "A corner that eases into the edge instead of kinking. Superellipse, dumped as an SVG path.",
    [
      "A normal rounded corner has a tiny kink where it meets the flat. You feel it before you can name it. A squircle ramps the curve so it flows.",
      "The playground draws the same chip twice. One is the squircle. One is the round-rect people actually ship. Look at the corner, not the label.",
    ],
    "squircle",
  ),
  study(
    "arcade-pixel",
    "Arcade pixel",
    ["WebGL", "Type"],
    "A word printed so hard its edges break into blocks. There is no pixel grid. One threshold cuts a soft edge.",
    [
      "It looks pixelated and there is no pixel grid anywhere. The word is drawn tiny and blown up, so every little sample becomes a square.",
      "Type your own word. The two sliders that matter are threshold and grid.",
    ],
    "arcade-pixel",
  ),
  study(
    "holo",
    "Holo card",
    ["CSS", "3D"],
    "Tilt it and the foil catches the light. Hearts come up on the side you turned. The photo flips its colours.",
    [
      "I rebuilt an identity card as foil. The card tilts toward the pointer. The photo is a different material, so it never reads as a hole in the same sheet.",
      "Play with the tilt. The foil is the whole point.",
    ],
    "holo",
    {
      credit: { source: "airbnb.com", href: "https://www.airbnb.com" },
    },
  ),
  study(
    "pixel-brushes",
    "Pixel brushes",
    ["Canvas", "Brush"],
    "A brush is one small shape stamped along a path. A few numbers decide if it's a line or a spray.",
    [
      "I wanted brushes that were just stamps. Same code. Different numbers. Crisp ribbon, dense spray, loose squares.",
      "Draw in the playground. The mark is the settings, not a texture file.",
    ],
    "pixel-brushes",
  ),
  study(
    "fade-motion",
    "Fade motion",
    ["WebGL", "Type"],
    "A word that trails into light. Nothing is blurred. Hundreds of copies, each a step lower.",
    [
      "I thought this was a blur. It's stacked copies of the word, almost invisible, and the fade is where a lot of them piled up.",
      "The dumb version drew two hundred times a frame and choked when you moved. Now each pixel walks back up the trail and counts.",
    ],
    "fade-motion",
  ),
  study(
    "liquid-ui",
    "Liquid UI",
    ["SVG", "SDF"],
    "Cards that fuse when they get close. The join bends inward, like they were poured.",
    [
      "I like UI where two cards become one soft surface instead of two boxes. This is a tiny engine that makes that join from code.",
      "Drag the cards. One knob goes from a crisp joint to goo.",
    ],
    "liquid-ui",
  ),
  study(
    "kinetic-typography",
    "Kinetic type",
    ["Canvas", "Type"],
    "One letter cut into tiles. Each tile rides its own wave, so the glyph ripples like cloth.",
    [
      "A letter is a grid. Each cell slips on a different phase, so the whole thing reads as cloth instead of a stamp.",
    ],
    "kinetic-typography",
  ),
  study(
    "ransom-note",
    "Ransom note",
    ["Type", "Collage"],
    "Every letter torn from a different magazine and taped crooked. Built from real cut-out scraps.",
    [
      "I always liked the kidnapper-note look. Each character picks a scrap, then gets a small tilt and bounce so the line feels assembled by hand.",
      "Type your own note and re-roll the scraps.",
    ],
    "ransom-note",
    {
      credit: { source: "resourceboy.com", href: "https://resourceboy.com/" },
    },
  ),
  study(
    "chroma-glow",
    "Chromatic glow",
    ["WebGL", "Glow"],
    "A word that glows and splits warm and cool at the edges, like a lens that can't quite focus.",
    [
      "The word gets blurred at a few sizes and added back, so it glows for real. Then a warm copy and a cool copy drift apart. That gap is the rainbow edge.",
      "Move over it and the split leans toward the cursor.",
    ],
    "chroma-glow",
  ),
  study(
    "emboss",
    "Realistic emboss",
    ["WebGL", "Texture"],
    "A word pushed into plaster, with the light catching the edges.",
    [
      "Type a word or drop an SVG. Depth, angle, grain. The presets are the honest starting points.",
    ],
    "emboss",
  ),
  study(
    "color-depth",
    "The art of color depth",
    ["CSS", "Buttons"],
    "Buttons that look like objects. Gloss, metal, cushions. Gradients and inset shadows stacked on one node.",
    [
      "They look expensive and slow. They are neither. A gradient body, inset bevel, a brighter hover layer, a soft bar of light along the top.",
      "Ten materials. Switch and steal the CSS.",
    ],
    "color-depth",
  ),
  study(
    "sandbox",
    "Symbols effect",
    ["WebGL", "Halftone"],
    "An image cut into brightness bands. Each band gets a tiny stamped symbol and its own colour.",
    [
      "The picture is rebuilt out of marks. It runs on the GPU, so video can play through it live.",
    ],
    "sandbox",
  ),
  study(
    "dia-gradient",
    "Dia's gradient",
    ["SVG", "Gradient"],
    "A green glow that rises from the floor. Blurred columns, tallest in the middle.",
    [
      "A few tall rectangles in one SVG, painted with the same greens as this site and blurred until they melt. On the footer it stays flat until you scroll it into view, then it grows from the bottom.",
    ],
    "dia-gradient",
    {
      credit: { source: "diabrowser.com", href: "https://www.diabrowser.com" },
    },
  ),
  study(
    "vector-editor",
    "Figma frame",
    ["SVG", "Bezier"],
    "The selected-layer look. Blue box, corner handles, live size tag, dots you can drag.",
    [
      "Two small parts. One draws the blue box around anything. The other lets you grab the dots on a path and hands the new path back.",
    ],
    "vector-editor",
    {
      credit: { source: "figma.com", href: "https://figma.com" },
    },
  ),
  study(
    "amo",
    "Hover video",
    ["Video", "Hover"],
    "A small pill that plays a short clip on hover, then resets when you leave.",
    [
      "The puffy 3D letters are only a video. The button plays it and rewinds. Swap the clip and the word can be anything.",
    ],
    "amo",
    {
      credit: { source: "amo.co", href: "https://amo.co" },
    },
  ),
  study(
    "midjourney",
    "ASCII swirl",
    ["WebGL", "Type"],
    "A swirl of real letters that slowly spin into a logo. Not a video. Text moved by code.",
    [
      "Each letter is drawn once and reused. The middle spins fast. The edges barely move. After the text, a cheap TV pass: bend, split colour, scanlines.",
    ],
    "midjourney",
    {
      credit: {
        source: "midjourney.com/medical",
        href: "https://www.midjourney.com/medical",
      },
    },
  ),
  study(
    "glossy",
    "Glossy",
    ["CSS", "Buttons"],
    "A blue action with a sheen bar across the top. Depth is inset light, not a drop shadow.",
    [
      "The fill is a vertical gradient. A bright top highlight, a soft inner light, an inner bottom bevel. Hover lifts a blurred white bar.",
      "Press scale is 0.96. The label stays sharp over the paint.",
    ],
    "glossy",
  ),
  study(
    "glow",
    "Glow",
    ["CSS", "Buttons"],
    "Lit from inside. Hover turns the light up.",
    [
      "Deep blue fill with a bottom rim and two inner glows. The hover layer is the same button with the lamps brighter. No extra drop shadow doing the job.",
    ],
    "glow",
  ),
  study(
    "bevel",
    "Bevel",
    ["CSS", "Buttons"],
    "An extruded key. Hover lifts it. Press slams it down onto its own side.",
    [
      "The 3D bottom is stacked hard edges in the box-shadow. Pressing collapses that stack so it feels like a real key, not a scale trick.",
    ],
    "bevel",
  ),
  study(
    "flat",
    "Different type",
    ["CSS", "Buttons"],
    "The plain baseline of the same button. Same size, same type, less theatre.",
    [
      "I kept this next to the glossy one so you can see what the extra layers are actually doing.",
    ],
    "flat",
  ),
  study(
    "buttons",
    "Buttons",
    ["CSS", "Buttons"],
    "Four treatments of one Add member control. Depth is inset shadows.",
    [
      "Glossy, glow, bevel, and the flat one. Same height, same plus icon, same press. The material is the only change.",
    ],
    "buttons",
  ),
  study(
    "qr",
    "QR reveal",
    ["Canvas", "Motion"],
    "A QR that arrives. Particles fly a shared path, then settle into the modules.",
    [
      "I wanted a dissolve that still had a destination. The flight is the same. The payload is either a streak or its own dust.",
    ],
    "qr",
  ),
  study(
    "athlos",
    "Molten wordmark",
    ["Canvas", "Type"],
    "A word that resolves out of heat. Cyan sits furthest out. Red hugs the letter. White is the core.",
    [
      "One field, the word blurred, brightness read off a thermal ramp. Every column has its own ignite clock, so the heat crosses the word instead of arriving all at once.",
    ],
    "athlos",
  ),
  study(
    "loom",
    "Loom",
    ["CSS", "Motion"],
    "Ten strips of gradient leaning the same way, so the whole sheet moves as one.",
    [
      "I saw a weave like this and wanted it as a component. The bands don't generate a pattern so much as replay a lean.",
    ],
    "loom",
  ),
  study(
    "fade-grid",
    "Fade grid",
    ["Canvas", "Type"],
    "A name in a grid of bars. The only thing that changes is how wide each bar is.",
    [
      "Each bar knows how far it sits from the letter. That distance sets how long it takes to leave, so a letter hollows from the middle or shrinks from its edge.",
    ],
    "fade-grid",
  ),
  study(
    "warp-grid",
    "Warp grid",
    ["CSS", "Grid"],
    "An eight by eight field of tiles that answers the cursor. Near tiles shrink. The far side opens up.",
    [
      "Leave and it goes even again. The four states it reaches for are measured, not eyeballed.",
    ],
    "warp-grid",
  ),
  study(
    "ring-letters",
    "Ring letters",
    ["Canvas", "Type"],
    "Contour rings appear at the letter's edge and run inward until they die at its spine.",
    [
      "Type as topography. Rings are born at the glyph, travel in, and vanish at the skeleton.",
    ],
    "ring-letters",
  ),
  study(
    "acme-login",
    "Login",
    ["CSS", "Form"],
    "It starts as one button. Press it and that button becomes its place in a card that steps through email and a code.",
    [
      "The field behind it is a sheet of silk drawn as dither. Height changes each step. The inputs are real fields, 16 pixels, with labels.",
    ],
    "acme-login",
  ),
  study(
    "wave-grid",
    "Wave grid",
    ["CSS", "3D"],
    "A grid of two-sided cards, each turning a full 360 about a diagonal. The fold travels as one straight wave.",
    [
      "The phase is handed out as a plane across the grid, so it doesn't look like each tile has its own clock.",
    ],
    "wave-grid",
  ),
  study(
    "drag-button",
    "Draggable button",
    ["Pointer", "Motion"],
    "A disc that stretches on the screen axes. Sideways pull widens it. Downward pull makes it taller. Nothing squashes.",
    [
      "Drag it in a circle and the size holds while the shape turns. Each axis answers only its own share of the drag.",
    ],
    "drag-button",
  ),
  study(
    "op-grid",
    "Op grid",
    ["CSS", "Type"],
    "A heading sitting in an optical grid. The lines do the weight. The type stays still.",
    [
      "Intent, then a line of body. The grid is a mask, not a texture slapped on top.",
    ],
    "op-grid",
  ),
  study(
    "island",
    "Island avatar",
    ["CSS", "Filter"],
    "An avatar squeezed out of a Dynamic Island. The neck gradient isn't drawn. Blur mixes the black into the colour.",
    [
      "Gooey blur plus contrast is the join. Then it throws hearts, which is the bit I added because it made me laugh.",
    ],
    "island",
  ),
  study(
    "loader",
    "Loader",
    ["CSS", "Filter"],
    "The same metaball trick as the island, used as a loader.",
    [
      "Three discs, blur, contrast. If you already have the island, the loader is free.",
    ],
    "loader",
  ),
  study(
    "accounts",
    "Hold to delete",
    ["Pointer", "Motion"],
    "Hold the row and the account is eaten. Let go and it comes back from exactly where it got to.",
    [
      "Progress is the only state. There is no confirm dialog pretending you didn't mean it. Hold is the confirm.",
    ],
    "accounts",
  ),
  study(
    "pipeline",
    "Pipeline board",
    ["UI", "Board"],
    "Kanban and list of the same leads. Click a card and it changes stage.",
    [
      "I wanted both views to share the data so the board isn't a screenshot of one mode.",
    ],
    "pipeline",
  ),
  study(
    "kanban",
    "Kanban",
    ["UI", "Board"],
    "Two columns. To call and Called. Click a lead to move it.",
    ["Same data as the list. The card is the control."],
    "kanban",
  ),
  study(
    "list",
    "List",
    ["UI", "Board"],
    "The same pipeline as a stack of rows.",
    ["When the board is too cute, this is the honest version."],
    "list",
  ),
  study(
    "icons",
    "Animated icons",
    ["SVG", "Icons"],
    "A small set of icons that carry the action in the stroke.",
    [
      "Plus, search, save, done. One stroke weight, currentColor, 44px hit targets because they sit alone.",
    ],
    "icons",
  ),
  study(
    "charts",
    "Charts",
    ["Canvas", "Data"],
    "Series drawn as small square tiles that drift, not a flat fill. Numbers count. You can change the window.",
    [
      "The data keeps a texture. A flat area chart looked like a screenshot. Tiles made it feel like it was still being counted.",
    ],
    "charts",
  ),
  study(
    "pie",
    "Pie chart",
    ["Canvas", "Data"],
    "A donut whose slices re-angle when the window changes.",
    ["Centre total follows the period, not the hover."],
    "pie",
  ),
  study(
    "bar",
    "Bar chart",
    ["Canvas", "Data"],
    "Bars as fields of square tiles. A period change morphs height instead of snapping.",
    ["Hover one band and the rest dim. Colour isn't the only cue. The tiles get bigger too."],
    "bar",
  ),
  study(
    "line",
    "Line chart",
    ["Canvas", "Data"],
    "A line you can window to 7, 14, or 30 days. Tabular numbers, so the total doesn't jump.",
    ["Scrubbing belongs here. I haven't wired a day tooltip yet. The line is the study."],
    "line",
  ),
  study(
    "dropdown",
    "Gooey dropdown",
    ["CSS", "Menu"],
    "The bead falls, the neck pinches off, then the sheet expands. It shouldn't stick to the trigger while it's opening.",
    [
      "Escape closes it. The options are a real listbox. Unlimited, 30-day pass, 10-class pack, Drop-in.",
    ],
    "dropdown",
  ),
  study(
    "dialog",
    "Member dialog",
    ["HTML", "Dialog"],
    "Add member in a native dialog. Inner radius is outer radius minus padding, so nested corners stay parallel.",
    [
      "The trigger gets focus back on close. Name and email have labels. Cancel is a verb.",
    ],
    "dialog",
  ),
  study(
    "sidebars",
    "Sidebars",
    ["UI", "Nav"],
    "A sidebar where the only flex is spacing. Padding stays even. The active row is a shape, not a colour shout.",
    [
      "I make a lot of these. The boring part is the part that matters. Home, Admissions, Members, same inset every time.",
    ],
    "sidebars",
  ),
  study(
    "fohe",
    "Admissions board",
    ["UI", "Board"],
    "A CRM slice. Waiting, ready for review, decided. Cards, not a table pretending to be a board.",
    ["Built to look like the console I keep sketching. Dummy applicants. No fake phone numbers."],
    "fohe",
  ),
  study(
    "oymo",
    "Scan frame",
    ["UI", "Camera"],
    "A lilac scan square. Dashed inner radius sits inside the outer one on purpose.",
    ["Ornaments later. The frame is the component. Concentric corners, 16px of padding, inner radius follows."],
    "oymo",
  ),
  study(
    "spina",
    "Expense list",
    ["UI", "List"],
    "A dark list of expenses. Tabular amounts so 84 and 1,200 don't shove the layout.",
    ["Rent, print, tools. The row is the hit target."],
    "spina",
  ),
];
